### ISSUE TITLE
Ink file cannot be read

### ISSUE THREAD

**Issue by darmawanalbert** [gamelab-vixio/front-end-redux#4]
<img width="1040" alt="screen shot 2018-09-10 at 11 08 25" src="https://user-images.githubusercontent.com/12585587/45276004-1146ce00-b4ea-11e8-9d93-6048573053b5.png">

**Comment by shanvaldo** [comment]
@darmawanalbert Bet ini npm nya engga d majuin kan versionnya?

**Comment by darmawanalbert** [comment]
The minimum inkVersion is 18
